MR24FDB1 Driver: MR24FDB1 Class Reference
MR24FDB1 Class Reference
MR24FDB1 class.
#include <mr24fdb1.h>
Classes
struct Packet_t
Packet struct / uinion
Public Types
enum FuncClasses {
GET = 0x01, SET = 0x02, RESPONCE = 0x03, REPORT = 0x04,
FALL = 0x06
}
Class of functions.
enum FuncGroups {
IDENT = 0x01, UNDEF_CLASS = 0x02, RADAR = 0x03, SYSTEM = 0x04,
OTHER = 0x05, FALLC = 0x05
}
Group of functions.
enum Functions {
DEVICE = 0x01, HEARTBEAT = 0x01, SOFTWARE = 0x02, HARDWARE = 0x03,
PROTOCOL = 0x04, REBOOT = 0x04, PRESENCE = 0x05, MOVEMENT = 0x06,
LOCATION = 0x07, UPGRADE = 0x08, UPGRADE_PKT = 0x09, INIT_SUCCESS = 0x0A,
END_OF_UPGRADE = 0x0A, FALL_ENABLE = 0x0B, SENSITIVITY = 0x0C, FALL_WARN_TIME = 0x0C,
UNKONWN_FUNC_D = 0x0D, FALL_SENSITIVITY = 0x0E, UNKONWN_FUNC_F = 0x0F, SCENE = 0x10,
UNKONWN_FUNC_11 = 0x11, UNOCCUPIED_TIME = 0x12
}
Function codes.
enum Presence_t { P_NOBODY = 0x00, P_PRESENT = 0x01, P_MOVING = 0x02 }
Presence states.
enum Location_t {
L_STATIONARY = 0x01, L_CLOSE = 0x02, L_AWAY = 0x03, L_APROACHING = 0x04,
L_LEAVING = 0x05
}
Location / Direction states.
enum HeartBeat_t { HB_NONE = 0x00, HB_STATIONARY = 0x01, HB_MOVEMENT = 0x02 }
Heartbeat states.
enum Scene_t {
DEFAULT_SC = 0x00, AREA_DETECT_SC = 0x01, BATHROOM_SC = 0x02, BEDROOM_SC = 0x03,
LIVING_ROOM_SC = 0x04, OFFICE_SC = 0x05, HOTEL_SC = 0x06
}
Scene settings.
enum UnoccupiedTime_t {
UT_NONE = 0x00, UT_10S = 0x01, UT_30S = 0x02, UT_1M = 0x03,
UT_2M = 0x04, UT_5M = 0x05, UT_10M = 0x06, UT_30M = 0x07,
UT_60M = 0x08
}
Unoccupied timeout values.
enum FallGroups { F_ALARM_CL = 0x01 }
Fall Radar report groups.
enum FallFunctions { F_ALARM = 0x01, F_WARNING = 0x02 }
Fall Function Codes in fall reports.
enum FallAlarm_t { F_SUSPECTED = 0x00, F_REAL = 0x01, F_NO_FALL = 0x02, NO_FALL_DATA = 0xFF }
Fall Alarm types.
enum FallWarnCount_t {
NO_FALL_WARNING = 0x00, FALL_WARNING_1 = 0x01, FALL_WARNING_2 = 0x02, FALL_WARNING_3 = 0x03,
FALL_WARNING_4 = 0x04
}
Fall Warning Types.
enum FallWarnTime_t {
MIN_1 = 0x00, MIN_2 = 0x01, MIN_3 = 0x02, MIN_4 = 0x03,
MIN_5 = 0x04, MIN_6 = 0x05, MIN_7 = 0x06, MIN_10 = 0x07,
MIN_15 = 0x08, MIN_30 = 0x09
}
Fall Warning time setting.
enum Result_t {
Res_Ok = 0x00, Res_Init, Res_Presence, Res_Movement,
Res_Location, Res_HeartBeat, Res_Reset, Res_Fall,
Res_UpgradeInProgress, Res_UpgradeSuccess, Res_InitSuccess, Res_Undefined,
Res_DeviceId_Rsp, Res_SoftwareVer_Rsp, Res_HardwareVer_Rsp, Res_ProtocolVer_Rsp,
Res_Presence_Rsp, Res_Movement_Rsp, Res_Sensitivity_Rsp, Res_Scene_Rsp,
Res_UnoccupiedTime_Rsp, Res_UpgradeStartOk_Rsp, Res_UpgradePacketAck_Rsp, Res_FallSensitivity_Rsp,
Res_FallEnable_Rsp, Res_FallWarnTime_Rsp, Res_Error = 100, Res_Unimplmented,
Res_Timeout, Res_PacketToLong, Res_UnknownPktClass, Res_Unexpected_Get,
Res_Unexpected_Set, Res_InvCrc, Res_NoPacketReceived, Res_InvRsp,
Res_InvRspGroup, Res_InvRspFunc, Res_InvRep, Res_InvRepGroup,
Res_InvRepFunc, Res_InvIdentFunc, Res_InvRadarFunc, Res_InvLocation,
Res_InvPresence, Res_InvOtherFunc, Res_InvHeartBeat, Res_InvReset,
Res_InvScene, Res_InvUnoccupiedTime, Res_InvFallGroup, Rea_InvFallAlarmFunc,
Res_InvFallAlarm, Res_InvFallWarnCount, Res_InvFallWarnTime, Res_UpgradeStartFail_Rsp,
Res_UpgradeFail
}
General result codes.
Public Member Functions
MR24FDB1 (uint8_t rxBit, uint8_t txBit)
Constructor.
MR24FDB1 ()
Result_t init ()
initalize radar
Result_t readByte (uint8_t *inByte)
get one byte from serial
Result_t readPacket ()
get a packet from the chip
Result_t parsePacket ()
parse packet
Result_t sendGetAndWait (FuncGroups fGroup, Functions func, Result_t responce)
send a "GET" packet to the module and wait for responce
void sendGet (FuncGroups fGroup, Functions func)
send a "GET" packet to the module
Result_t waitFor (Result_t waitResult)
wait until packet of the specified type is recieved
string & getDeviceId ()
requests Device Id
string & getSoftwareVer ()
requests Software verion
string & getHardwareVer ()
requests Hardware version
string & getProtocolVer ()
request Protocol Version
Presence_t getPresence (long age=0)
get presence from module
long getPresenceTs ()
return last time stamp for presence
float getMovement (long age=0)
get movement
long getMovmentTs ()
return last time stamp for movement
Location_t getLocation ()
get location
long getLocationTs ()
return last time stamp for location
HeartBeat_t getHeartBeat ()
get Heartbeat
long getHeartBeatTs ()
return last time stamp for heartbeat
uint8_t getSensitivity (long age=0)
get sensitivity parameter
long getSensitivity_ts ()
return last time stamp for sensitivity
Scene_t getScene (long age=0)
get scene parameter
long getScene_ts ()
return last time stamp for scene
UnoccupiedTime_t getUnoccupiedTime ()
get unoccupied timeout parameter
long getUnoccupiedTime_ts ()
return last time stamp for unoccupied timer
bool getFallEnable (long age)
get status of fall enable switch
FallWarnTime_t getFallWarnTime (long age)
get status of fall warning time setting
uint8_t getFallSensitivity (long age)
get status of fall sensitivty setting
void sendSet (FuncGroups group, Functions func, uint8_t val, uint16_t len)
send a "GET" packet to the module
void setSensitivity (uint8_t sensVal)
set sensitivity
void setScene (Scene_t newScene)
set scene
void setUnoccupiedTime (UnoccupiedTime_t time)
set unoccupied timeut
Result_t reboot ()
reboot
void startUpgrade (uint32_t size, uint8_t *versionP, uint16_t verLen)
send an upgrade packet
void sendUpgradePacket (uint32_t offset, uint8_t *packetP)
send an upgrade packet
void endOfUpgrade ()
Send end of upgrade packet.
void setFallDetect (bool onOff)
enable / disable fall detection
void setFallWarnTime (FallWarnTime_t fallTime)
set fall warn time parameter
void setFallSensitivity (uint8_t sensVal)
set fall detection sensitivity
void dumpPacket (int length=0)
dumpt packet in hex/asci format
Result_t testSend ()
send test
Public Attributes
const uint8_t MESSAGE_HEAD = 0x55
Data frame header.
uint8_t RXBit
uint8_t TXBit
Packet_t Packet
incoming packet from radar module
bool PacketReceived = false
a valid packet has been received
Result_t Status
Current status running fault, reset....
long Status_ts
Last time changed.
Result_t UpgradeStatus
long UpgradeStatus_ts
Presence_t Presence
last active report Envrioment Status
long Presence_ts
Presence time stamp.
float Movement
movment strengtht
long Movement_ts
time stamp;
Location_t Location
location far, close none
long Location_ts
time stamp;
HeartBeat_t HeartBeat
Heartbeat detection.
long HeartBeat_ts
time stamp;
uint8_t Sensitivity
senstitivity setting 0-0x0A
long Sensitivity_ts
time stamp;
Scene_t Scene
Scene setting.
long Scene_ts
Time stamp.
UnoccupiedTime_t UnoccupiedTime
Unoccupied time.
long UnoccupiedTime_ts
Time stamp.
bool FallEnable
long FallEnable_ts
FallAlarm_t FallAlarm
latest fall status
long FallAlarm_ts
time stamp;
FallWarnCount_t FallWarning
last fallwarning received
long FallWarning_ts
time stamp;
FallWarnTime_t FallWarnTime
last fallwarning time received
long FallWarnTime_ts
time stamp;
uint8_t FallSensitivity
last fallwarning received
long FallSensitivity_ts
time stamp;
bool UpgradeStartAck
long UpgradeStartAck_ts
string DeviceId
device id
string SoftwareVer
Software Version.
string HardwareVer
Software Version.
string ProtocolVer
Protocl Version.
bool GotResponce
Static Public Attributes
static const int DEVICE_ID_LEN =12
Length of device id data.
static const int HARDWARE_VER_LEN =8
Length of hardware version data.
static const int SOFTWARE_VER_LEN =8
Lenght of software version data.
static const int PROTOCOL_VER_LEN =8
Length of protocol version data.
static const int MAXPACKET_DATA_LENGTH = 50
max data length
static const unsigned long MAX_SERIAL_WAIT_TIME = 2000
max time in ms to wait for serial char to arrive
static const int MAXPACKET_LENGTH = sizeof(Packet_t)
max length of a packet from the chip
static const char * ClassStr []
string representations of code/class/func/Scene etc
static const int ClassStrCount =COUNT(ClassStr)
Number of function class strings.
static const char * GroupStr []
Text representation of function groups.
static const int GroupStrCount = COUNT(GroupStr)
Number of function group strings.
static const char * FuncStr []
Text representation of functions.
static const int FuncStrCount = COUNT(FuncStr)
Number of function strings.
static const char * SceneStr []
Text representation of scenes.
static const int SceneStrCount = COUNT(SceneStr)
Number of function strings.
static const char * UnoccupiedTimeStr []
Text represntations of Unoccupied settings.
static const int UnoccupiedTimeStrCount = COUNT(SceneStr)
Number of Unoccupied settings strings.
Private Member Functions
Result_t decodeRadar (FuncClasses fClass)
parse Radar group responces and reports
void sendPacket (uint8_t *txPacket, int len)
send a packet to the module
Result_t parseResponce ()
parse reponce type packet
Result_t parseReport ()
parse report type packet
Result_t parseFallReport ()
parse fall type packet
uint16_t calculateCrc16 (uint8_t *frameP, uint16_t len)
calculate crc16 of current packet
uint16_t calculateCrc16 ()
calculate crc16 of current packet
uint16_t addCrc16 (uint8_t *frameP, uint16_t len)
calculate and add crc16 at end of buffer
Friends
class MR24FDB_Exception
Detailed Description
MR24FDB1 class.
Class to handle comunicating with the mr24fdb1 radar module
Definition at line 267 of file mr24fdb1.h.
Member Enumeration Documentation
enum MR24FDB1::FuncClasses
Class of functions.
First byte of packet (not counting length) indicates the class the packet belongs to
Enum Values Documentation
GET
Read Operation.
SET
Write Operation.
RESPONCE
Respones from GET and SET commands.
REPORT
Active continnous reports.
FALL
Fall reports.
Definition at line 349 of file mr24fdb1.h.
     enum FuncClasses
     {
         GET             = 0x01,
         SET             = 0x02,
         RESPONCE        = 0x03,
         REPORT          = 0x04,
         FALL            = 0x06,
     };
enum MR24FDB1::FuncGroups
Group of functions.
They are chared over GET, SET, RESPONCE, FALL type packets but FALL has its own groups and functions
Enum Values Documentation
IDENT
Identifications and versions.
UNDEF_CLASS
Undef group.
RADAR
Radar / Senor.
SYSTEM
Sytemt related.
OTHER
Other functions.
FALLC
Fall group used mainly in get...
Definition at line 363 of file mr24fdb1.h.
     enum FuncGroups
     {
         IDENT           = 0x01,
         UNDEF_CLASS     = 0x02,
         RADAR           = 0x03,
         SYSTEM          = 0x04,
         OTHER           = 0x05,
         FALLC           = 0x05,
     };
enum MR24FDB1::Functions
Function codes.
third byte indicates specific function
Enum Values Documentation
DEVICE
HEARTBEAT
SOFTWARE
HARDWARE
PROTOCOL
REBOOT
PRESENCE
MOVEMENT
LOCATION
UPGRADE
UPGRADE_PKT
INIT_SUCCESS
END_OF_UPGRADE
FALL_ENABLE
Fall get/responce enable switch.
SENSITIVITY
Movement sensitivity.
FALL_WARN_TIME
UNKONWN_FUNC_D
FALL_SENSITIVITY
Fall get/set sensititvity.
UNKONWN_FUNC_F
SCENE
UNKONWN_FUNC_11
UNOCCUPIED_TIME
Definition at line 377 of file mr24fdb1.h.
     enum Functions {
         DEVICE              = 0x01,
         HEARTBEAT           = 0x01,
         SOFTWARE            = 0x02,
         HARDWARE            = 0x03,
         PROTOCOL            = 0x04,
         REBOOT              = 0x04,
         PRESENCE            = 0x05,
         MOVEMENT            = 0x06,
         LOCATION            = 0x07,
         UPGRADE             = 0x08,
         UPGRADE_PKT         = 0x09,
         INIT_SUCCESS        = 0x0A,
         END_OF_UPGRADE      = 0x0A,
         FALL_ENABLE         = 0x0B,
         SENSITIVITY         = 0x0C,
         FALL_WARN_TIME      = 0x0C,
         UNKONWN_FUNC_D      = 0x0D,
         FALL_SENSITIVITY    = 0x0E,
         UNKONWN_FUNC_F      = 0x0F,
         SCENE               = 0x10,
         UNKONWN_FUNC_11     = 0x11,
         UNOCCUPIED_TIME     = 0x12,
     };
enum MR24FDB1::Presence_t
Presence states.
Enum Values Documentation
P_NOBODY
No presence detected.
P_PRESENT
Somebody Present and stationary.
P_MOVING
Somebody present and moving.
Definition at line 407 of file mr24fdb1.h.
     enum Presence_t
     {
         P_NOBODY            = 0x00,
         P_PRESENT           = 0x01,
         P_MOVING            = 0x02,
     };
enum MR24FDB1::Location_t
Location / Direction states.
Enum Values Documentation
L_STATIONARY
No one or stationary.
L_CLOSE
Something close.
L_AWAY
Something far.
L_APROACHING
Something aproaching.
L_LEAVING
Something leaving.
Definition at line 425 of file mr24fdb1.h.
     enum Location_t
     {
         L_STATIONARY        = 0x01,
         L_CLOSE             = 0x02,
         L_AWAY              = 0x03,
         L_APROACHING        = 0x04,
         L_LEAVING           = 0x05
     };
enum MR24FDB1::HeartBeat_t
Heartbeat states.
Enum Values Documentation
HB_NONE
No presence detected.
HB_STATIONARY
Presence detecte and stationary.
HB_MOVEMENT
Presence detected and moving.
Definition at line 446 of file mr24fdb1.h.
     enum HeartBeat_t
     {
         HB_NONE             = 0x00,
         HB_STATIONARY       = 0x01,
         HB_MOVEMENT         = 0x02,
     };
enum MR24FDB1::Scene_t
Scene settings.
Enum Values Documentation
DEFAULT_SC
Default setting at power on.
AREA_DETECT_SC
General Area detect.
BATHROOM_SC
Bathroom top mounted.
BEDROOM_SC
Bedroom top mounted.
LIVING_ROOM_SC
Living room top mounted.
OFFICE_SC
Office top mounted.
HOTEL_SC
Hotell top mounted (room?? foayer ?? restroom ?? hallway ??)
Definition at line 463 of file mr24fdb1.h.
     enum Scene_t {
         DEFAULT_SC              = 0x00,
         AREA_DETECT_SC          = 0x01,
         BATHROOM_SC             = 0x02,
         BEDROOM_SC              = 0x03,
         LIVING_ROOM_SC          = 0x04,
         OFFICE_SC               = 0x05,
         HOTEL_SC                = 0x06,
     };
enum MR24FDB1::UnoccupiedTime_t
Unoccupied timeout values.
Enum Values Documentation
UT_NONE
"Do not use forced entry unnoccupied function"
UT_10S
10 Sec
UT_30S
30 Sec
UT_1M
1 Minute
UT_2M
2 Minutes
UT_5M
5 Minutes
UT_10M
10 Minutes
UT_30M
30 Minutes
UT_60M
60 Minutes
Definition at line 476 of file mr24fdb1.h.
     enum UnoccupiedTime_t {
         UT_NONE                 = 0x00,
         UT_10S                  = 0x01,
         UT_30S                  = 0x02,
         UT_1M                   = 0x03,
         UT_2M                   = 0x04,
         UT_5M                   = 0x05,
         UT_10M                  = 0x06,
         UT_30M                  = 0x07,
         UT_60M                  = 0x08,
     };
enum MR24FDB1::FallGroups
Fall Radar report groups.
Fall alarm as all of its own groups
Enum Values Documentation
F_ALARM_CL
Definition at line 495 of file mr24fdb1.h.
     enum FallGroups {
         F_ALARM_CL              = 0x01      // Fallradar actually only has one group , but for consistensy...
     };
enum MR24FDB1::FallFunctions
Fall Function Codes in fall reports.
< Alarm has all its own groups
Enum Values Documentation
F_ALARM
fall info
F_WARNING
alarm time points
Definition at line 501 of file mr24fdb1.h.
     enum FallFunctions
     {
         F_ALARM                 = 0x01,
         F_WARNING               = 0x02,
     };
enum MR24FDB1::FallAlarm_t
Fall Alarm types.
Enum Values Documentation
F_SUSPECTED
Only suspected fall.
F_REAL
An actuall fall.
F_NO_FALL
No fall detected.
NO_FALL_DATA
No Fall data aquired.
Definition at line 509 of file mr24fdb1.h.
     enum FallAlarm_t
     {
         F_SUSPECTED             = 0x00,
         F_REAL                  = 0x01,
         F_NO_FALL               = 0x02,
         NO_FALL_DATA            = 0xFF,
     };
enum MR24FDB1::FallWarnCount_t
Fall Warning Types.
Enum Values Documentation
NO_FALL_WARNING
No warning issued yet.
FALL_WARNING_1
First Warning at 5 min.
FALL_WARNING_2
Second Warning at 10 min.
FALL_WARNING_3
Third Warning at 30 min.
FALL_WARNING_4
Fourth Warning at 60 min.
Definition at line 519 of file mr24fdb1.h.
     enum FallWarnCount_t {
         NO_FALL_WARNING         = 0x00,
         FALL_WARNING_1          = 0x01,
         FALL_WARNING_2          = 0x02,
         FALL_WARNING_3          = 0x03,
         FALL_WARNING_4          = 0x04,
     };
enum MR24FDB1::FallWarnTime_t
Fall Warning time setting.
Enum Values Documentation
MIN_1
1 Minute Warn time
MIN_2
2 Minutes Warn time
MIN_3
3 Minutes Warn time
MIN_4
4 Minutes Warn time
MIN_5
5 Minutes Warn time
MIN_6
6 Minutes Warn time
MIN_7
7 Minutes Warn time
MIN_10
10 Minutes Warn time
MIN_15
15 Minutes Warn time
MIN_30
30 Minutes Warn time
Definition at line 529 of file mr24fdb1.h.
     enum FallWarnTime_t {
         MIN_1                   = 0x00,
         MIN_2                   = 0x01,
         MIN_3                   = 0x02,
         MIN_4                   = 0x03,
         MIN_5                   = 0x04,
         MIN_6                   = 0x05,
         MIN_7                   = 0x06,
         MIN_10                  = 0x07,
         MIN_15                  = 0x08,
         MIN_30                  = 0x09
     } ;
enum MR24FDB1::Result_t
General result codes.
stuff before Res_Error are status returns after Res_Error are error/fail/fault conditions
!!!!!!! If you move / add to this you need to add to ResStr and / or ErrStr in decodeError.cpp to keep them in sync
Enum Values Documentation
Res_Ok
All ok no errors.
Res_Init
In Init process.
Res_Presence
Presence detected.
Res_Movement
Movment strength.
Res_Location
Location report received.
Res_HeartBeat
HeartBeat info.
Res_Reset
A reset has occured.
Res_Fall
Fall type report received.
Res_UpgradeInProgress
Upgrade in progess state, !! upgrades not implemented yet !!
Res_UpgradeSuccess
Returned on succsesfull upgrade !! upgrades not implemented yet !!
Res_InitSuccess
Returned after successful initialization.
Res_Undefined
Undefined status.
Res_DeviceId_Rsp
Device id responce.
Res_SoftwareVer_Rsp
Sofware Version responce.
Res_HardwareVer_Rsp
Hardware Version responce.
Res_ProtocolVer_Rsp
Protocol Version responce.
Res_Presence_Rsp
Presence responce.
Res_Movement_Rsp
Movement responce.
Res_Sensitivity_Rsp
Sensitivty responce.
Res_Scene_Rsp
Scene resoonce.
Res_UnoccupiedTime_Rsp
Unoccupied timer responce.
Res_UpgradeStartOk_Rsp
Upgrade start ack responce.
Res_UpgradePacketAck_Rsp
Upgrade packet ack responce.
Res_FallSensitivity_Rsp
Fall Sensitivity responce.
Res_FallEnable_Rsp
Fall enable switch responce.
Res_FallWarnTime_Rsp
Fall Warning time responce.
Res_Error
Res_Unimplmented
Unimplemented function called.
Res_Timeout
Timed out waiting on Serial port.
Res_PacketToLong
Packet lenght longer than spec.
Res_UnknownPktClass
Uknown packet class (Packet Code) not one of Packet_t.
Res_Unexpected_Get
GET packets should not be sent fron the module.
Res_Unexpected_Set
SET packets should not be sent fron the module.
Res_InvCrc
crc calculation does not match packet crc
Res_NoPacketReceived
No valid packet was received.
Res_InvRsp
Invalid Responce.
Res_InvRspGroup
Invalid Resonce group was reseviced.
Res_InvRspFunc
Invalid Responce function.
Res_InvRep
Invalid Activer report.
Res_InvRepGroup
Invalid Active report group was reseviced.
Res_InvRepFunc
Invalid Active Report functions.
Res_InvIdentFunc
Invalid identfication function recevice.
Res_InvRadarFunc
Invalid radar function code was received.
Res_InvLocation
Invalid location indicator received.
Res_InvPresence
Invalid Presence code received.
Res_InvOtherFunc
Invalid Other report func.
Res_InvHeartBeat
Invalid heartbeat code received.
Res_InvReset
Invalid Reset data byt should be 0x0f.
Res_InvScene
Invalid Scene id.
Res_InvUnoccupiedTime
Invalid unoccupied time.
Res_InvFallGroup
Invalid Fall group received (currnetly only 1 group defined)
Rea_InvFallAlarmFunc
Unvalid Fall Alarm Func received.
Res_InvFallAlarm
Invalid Fall alarm type received.
Res_InvFallWarnCount
Invalid Fall Warning count received.
Res_InvFallWarnTime
Invalid Fall Warning count received.
Res_UpgradeStartFail_Rsp
and upgrade atempt failed
Res_UpgradeFail
Upgrade failed.
Definition at line 550 of file mr24fdb1.h.
     enum Result_t
     {
 /* 0*/  Res_Ok = 0x00,
 /* 1*/  Res_Init,
 /* 2*/  Res_Presence,
 /* 3*/  Res_Movement,
 /* 4*/  Res_Location,
 /* 5*/  Res_HeartBeat,
 /* 6*/  Res_Reset,
 /* 7*/  Res_Fall,
 /* 8*/  Res_UpgradeInProgress,
 /* 9*/  Res_UpgradeSuccess,
 /*10*/  Res_InitSuccess,
 /*11*/  Res_Undefined,
 // responces
 /*12*/  Res_DeviceId_Rsp,
 /*13*/  Res_SoftwareVer_Rsp,
 /*14*/  Res_HardwareVer_Rsp,
 /*15*/  Res_ProtocolVer_Rsp,
 /*16*/  Res_Presence_Rsp,
 /*17*/  Res_Movement_Rsp,
 /*18*/  Res_Sensitivity_Rsp,
 /*19*/  Res_Scene_Rsp,
 /*20*/  Res_UnoccupiedTime_Rsp,
 /*21*/  Res_UpgradeStartOk_Rsp,
 /*22*/  Res_UpgradePacketAck_Rsp,
 /*23*/  Res_FallSensitivity_Rsp,
 /*24*/  Res_FallEnable_Rsp,
 /*25*/  Res_FallWarnTime_Rsp,
 // fault conditions below
 /*100*/ Res_Error = 100,
         Res_Unimplmented,
         Res_Timeout,
         Res_PacketToLong,
         Res_UnknownPktClass,
         Res_Unexpected_Get,
         Res_Unexpected_Set,
         Res_InvCrc,
         Res_NoPacketReceived,
 //
         // - Responce
         Res_InvRsp,
         Res_InvRspGroup,
         Res_InvRspFunc,
         // - Report
         Res_InvRep,
         Res_InvRepGroup,
         Res_InvRepFunc,
         // -- Identification
         Res_InvIdentFunc,
         // -- Radar
         Res_InvRadarFunc,
         Res_InvLocation,
         Res_InvPresence,
         // -- Other
         Res_InvOtherFunc,
         Res_InvHeartBeat,
         Res_InvReset,
         Res_InvScene,
         Res_InvUnoccupiedTime,
         // - Fall
         Res_InvFallGroup,
         Rea_InvFallAlarmFunc,
         Res_InvFallAlarm,
         Res_InvFallWarnCount,
         Res_InvFallWarnTime,
         Res_UpgradeStartFail_Rsp,
         Res_UpgradeFail,
 };
Constructor & Destructor Documentation
MR24FDB1::MR24FDB1 (uint8_t rxBit, uint8_t txBit)
Constructor.
Parameters
rxBit GPIO pin for rx default 16
txBit GPIO pin for tx default 17
< running status
< last active report Envrioment Status
< Presence time stamp
< movment strengtht
< time stamp
< presence location far, close none
< time stamp
< Heartbeat detection
Definition at line 96 of file mr24fdb1.cpp.
 MR24FDB1::MR24FDB1(uint8_t rxbit, uint8_t txbit) {
     PacketReceived=false;
     memset(&Packet,0,sizeof(Packet));
     Status = Res_Undefined;
     Status_ts = millis();
     UpgradeStatus = Res_Undefined;
     UpgradeStatus_ts = 0;
     Presence=P_NOBODY;
     Presence_ts=0;
     Movement=0;
     Movement_ts=0;
     Location=L_STATIONARY;
     Location_ts=0;
     HeartBeat=HB_NONE;
     HeartBeat_ts=0;
     Sensitivity=0;
     Sensitivity_ts=0;
     FallAlarm=NO_FALL_DATA;
     FallAlarm_ts=0;
     FallWarning=NO_FALL_WARNING;
     FallWarning_ts=0;
     FallSensitivity=0;
     FallSensitivity_ts=0;
     Scene = DEFAULT_SC;
     Scene_ts=0;
     UnoccupiedTime = UT_10S;
     UnoccupiedTime_ts=0;
     UpgradeStartAck = false;
     UpgradeStartAck_ts = 0;
     FallEnable=false;
     FallEnable_ts=0;
     RXBit = rxbit;
     TXBit = txbit;
     GotResponce=false;
     DeviceId[0]=SoftwareVer[0]=ProtocolVer[0]=0;
 }
References DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC, DEFAULT_SC.
MR24FDB1::MR24FDB1 () inline
Definition at line 699 of file mr24fdb1.h.
         MR24FDB1() : MR24FDB1(16,17) {};
Member Function Documentation
MR24FDB1::Result_t MR24FDB1::init ()
initalize radar
Returns
Res_Ok of successfull
Definition at line 152 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::init() {
     uint8_t aByte=0;
     MR24FDB1::Result_t retVal;
     INFO(" Radar Init\n");
     //Serial1.begin(9600, SERIAL_8N1, RXBit, TXBit);
     Serial2.begin(9600, SERIAL_8N1);
     delay(1000);
     INFO("Reading a packet");
     retVal=readPacket();
     //  Reboot seems do do nothing....
     //  It should give an init successfull responce
 //  retVal=reboot();
     Status=Res_Init;
     Status_ts=millis();
     INFO("Radar Init Done\n");
     return MR24FDB1::Res_Ok;
 }
References Res_Init, Res_Init, Res_Init, Res_Init, Res_Init.
Referenced by setup().
MR24FDB1::Result_t MR24FDB1::readByte (uint8_t * inByte)
get one byte from serial
Wait around for MaxTime ms for a byte to arrive returns Res_OK on success Res_Timeout on timeout
Parameters
inByte pointer where to store byte
Returns
Res_Ok on sucess
Definition at line 171 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::readByte(uint8_t * inByte) {
     unsigned long time;
     time = millis();
     while (Serial2.available() <= 0)
     {
         if(millis() - time > MAX_SERIAL_WAIT_TIME) {
           WARN("readByte Timeout\n");
           return MR24FDB1::Res_Timeout;
         }
     }
     *inByte = Serial2.read();
     return MR24FDB1::Res_Ok;
 }
References MAX_SERIAL_WAIT_TIME, MAX_SERIAL_WAIT_TIME, MAX_SERIAL_WAIT_TIME.
Referenced by readPacket().
MR24FDB1::Result_t MR24FDB1::readPacket ()
get a packet from the chip
Read a complete packet from the chip with crc check
Returns
MR24FDB1::Result_t Res_Ok if successfull.
Definition at line 191 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::readPacket()
 {
     uint8_t     inByte;                         // incoming byte
     int         lenCount = 0;                           // lenght counter
     bool        done = false;
     Result_t    retVal=MR24FDB1::Res_Ok;
     uint8_t     *pp;
     uint16_t    crc;
     uint16_t    pktCrc;
     uint16_t    pktLength = 0;
     unsigned long time;
     unsigned long maxTime;
     time = millis();
     maxTime = 1000;         // max millisec to wait
     PacketReceived = false;
     // wait for header
     inByte = 0;
     DBG3("readPacket: Waiting for start code\n");
     while (inByte != MESSAGE_HEAD) {
         if((retVal=readByte(&inByte)) != Res_Ok) return retVal;
     }
     Packet.frameStart=inByte;
     DBG3("Getting Length....:");
     // got length bytes yet ?
     while(lenCount<2) {
         if((retVal=readByte(&inByte)) != Res_Ok) return retVal;
         pktLength |= inByte<<(8*lenCount);
         lenCount++;
     }
     if (pktLength > MAXPACKET_LENGTH)  {
         DBG3NL;
         ERROR("Length (%d) to high, Aborting\n",pktLength);
         return Res_PacketToLong;
     }
     DBG3V_S("%d (%4.4x)",pktLength,pktLength);
     DBG3NL;
     Packet.length=pktLength;
     DBG3("Getting rest of packet\n");
     pp = ((uint8_t *) &Packet.funcClass) ; // step over length and header
     for (int pi = 2; pi <= pktLength;pi++) {        // pi=2 -> we alreade received 2 bytes and header doesn count
         if((retVal=readByte(&inByte)) != Res_Ok) return retVal;
         *pp++=inByte;
     }
     uint8_t *RawPkt = (uint8_t *)&Packet;
     pktCrc=RawPkt[pktLength] | (RawPkt[pktLength-1]<<8); // get crc at end of received packet
                                                          // and yes pktLength is a coorect index since the received length
                                                          // does not count the header byte...
     crc=calculateCrc16();                                       // Calculate actual crc on received packet
     if (pktCrc != crc){
         DBG3NL;
         ERROR("CRC Check Failed: PktCrc: %d (%4.4x), CaclCrc: %d (%4.4x)\n", pktCrc,pktCrc,crc,crc);
         throw MR24FDB1_Exception( Res_InvCrc,0,0,0,crc);
         return Res_InvCrc;
     }
     PacketReceived = true;
     return Res_Ok;
 }
References MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH, MAXPACKET_LENGTH.
Referenced by init(), init(), init(), init(), init().
MR24FDB1::Result_t MR24FDB1::parsePacket ()
parse packet
-----------------------— Parse incominig packets -------------------—
parse the incommig packet and set internal variables accordingly Throws and exception with class MR24FDB1_Exception in case of error
Returns
Resuslt_t xyz depending ong result
Definition at line 607 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::parsePacket() {
     DBG3("parsePacket :\n");
     switch(Packet.funcClass) {
         // can get and set ever happen as incomming from chip?
         case GET:                   // get data packet !!! can this even happen ??  return parseGet(); break;
         case SET:                   // Set data packet ??? can this happen on received data
             ERROR("Get / Set Packet received. This should not happen! (Func Class): %2.2x\n",Packet.funcClass);
             throw MR24FDB1_Exception( (Packet.funcClass==GET?Res_Unexpected_Get:Res_Unexpected_Set), Packet.funcClass,Packet.funcGroup,Packet.func);
             break;
         case RESPONCE:              // Passive report
             return parseResponce();
             break;
         case REPORT:
             return parseReport();
             break;
         case FALL:
             return parseFallReport();
             break;
         default:
             ERROR("Uknown Packet type (Func Class): %2.2x\n",Packet.funcClass);
             throw MR24FDB1_Exception( Res_UnknownPktClass, Packet.funcClass,Packet.funcGroup,Packet.func);
     }
 }
References FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL, FALL.
Referenced by testSend(), testSend(), testSend().
MR24FDB1::Result_t MR24FDB1::sendGetAndWait (FuncGroups fGroup, Functions func, Result_t responce)
send a "GET" packet to the module and wait for responce
Parameters
fGroup the function group to request
func the function to request
responce
Definition at line 301 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::sendGetAndWait(FuncGroups fGroup, Functions func,Result_t responce) {
     uint tries=0;
     bool done=false;
     MR24FDB1::Result_t result=Res_Ok;
     DBG3("SendGetAndWait for %2.2d% => s\n",responce,MR24FDB1_Exception::ResStr[responce] );
     while((result!=responce) && (tries++<5)) {
         DBG3("Sending GET resquest [%2.2d] of 5\n",tries);
         sendGet(fGroup,func);
         result=waitFor(responce);
     }
     if(result == Res_Timeout || tries>=5) {
         ERROR("getAndWait: Timeout waiting for (%2.2d) %s\n",responce, MR24FDB1_Exception::ResStr[responce]);
         throw MR24FDB1_Exception( Res_Timeout, GET,fGroup,func);
     }
     return result;
 }
References GET, GET, GET, GET, GET, GET.
Referenced by getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId(), getDeviceId().
void MR24FDB1::sendGet (FuncGroups fGroup, Functions func)
send a "GET" packet to the module
Parameters
fGroup the function group to request
func the function to request
Definition at line 290 of file mr24fdb1.cpp.
 void MR24FDB1::sendGet(FuncGroups fGroup, Functions func) {
     uint8_t txPacket[]={MESSAGE_HEAD,0x07,0x00,GET,fGroup,func,0x00,0x00};
     DBG3("Sending \"GET %s/%s\" packet",GroupStr[fGroup],FuncStr[func]);
     DBG3V_S(" (0x%2.2x/ 0x%2.2x)",fGroup,func);
     DBG3NL;
     addCrc16(txPacket,sizeof(txPacket));
     sendPacket(txPacket,sizeof(txPacket));
 }
References FuncStr, FuncStr, FuncStr, FuncStr, FuncStr, FuncStr.
Referenced by sendGetAndWait().
MR24FDB1::Result_t MR24FDB1::waitFor (Result_t waitResult)
wait until packet of the specified type is recieved
throws ans exception on error
TODO: timeout....
Parameters
waitResult result to wait for
Definition at line 320 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::waitFor(Result_t waitRes) {
     int count=1;
     Result_t result=Res_Error;
     DBG3V_S("waitFor: ");
     DBG3V_S(" %2.2d => %s",waitRes, MR24FDB1_Exception::ResStr[waitRes]);
     while(result!=waitRes && count<10) {        //timeout after 10 packets is more than enough
         result=readPacket();
         try {
             result=parsePacket();
             VERB_S("waitfor [%d] - Got %2.2d => %s\n",count++,result, (result<Res_Error) ? MR24FDB1_Exception::ResStr[result] : "");
         }
         catch (MR24FDB1_Exception e) {
             ERROR("waitfor %2.2d => %s\n",waitRes,  MR24FDB1_Exception::ResStr[waitRes]);
             e.decodeError();
         }
         count++;
     }
     if(count>=10) {
         WARN("waitFor: Timeut waiting for %2.2d = %s\n",waitRes, MR24FDB1_Exception::ResStr[waitRes]);
         result=Res_Timeout;
     }
     return result;
 }
References Res_Error, Res_Error, Res_Error, Res_Error, Res_Error, Res_Error.
Referenced by reboot(), reboot(), reboot().
string & MR24FDB1::getDeviceId ()
requests Device Id
if not yet cached sends a request for device id and stores it internally else return chached value throws exeption on error
Returns
pointer to DeviceId
Definition at line 345 of file mr24fdb1.cpp.
 string & MR24FDB1::getDeviceId() {
     DBG1("getDeviceId");
     if (DeviceId.length() == 0) {
         DBG1V_S(", No cache. Requesting from module ");
         sendGetAndWait(IDENT,DEVICE,Res_DeviceId_Rsp);  // might not come back, throws exception on timeout
     }
 #if IS_1V
     dbgHexDump((const uint8_t *)DeviceId.c_str(),DEVICE_ID_LEN,false);
 #endif
     DBG1NL;
     return DeviceId;
 }
References DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE.
string & MR24FDB1::getSoftwareVer ()
requests Software verion
if not yet chached sends a request for software version and stores it internally else return cached value throws exeption on error
Returns
string reference to SoftwareRev
Definition at line 359 of file mr24fdb1.cpp.
 string &  MR24FDB1::getSoftwareVer() {
         DBG1("getSoftwareVer"); if(SoftwareVer.length() == 0){
         DBG1V_S(" No cache requesting from module ");
         sendGetAndWait(IDENT,SOFTWARE,Res_SoftwareVer_Rsp);
     }
 #if IS_1V
     dbgHexDump((const uint8_t *)SoftwareVer.c_str(),SOFTWARE_VER_LEN,false);
 #endif
     DBG1NL;
     return SoftwareVer;
 }
string & MR24FDB1::getHardwareVer ()
requests Hardware version
if not yet cached sends a request for hardware version and stores it internally else returns cachec value throws exeption on error
Returns
string reference to HardwareRev
Definition at line 371 of file mr24fdb1.cpp.
 string & MR24FDB1::getHardwareVer() {
     DBG1("getHardwareVer");
     if(HardwareVer.length() == 0) {
         DBG1V_S(" No cache requesting from module ");
         sendGetAndWait(IDENT,HARDWARE,Res_HardwareVer_Rsp);
     }
 #if IS_1V
     dbgHexDump((const uint8_t *)HardwareVer.c_str(),HARDWARE_VER_LEN,false);
 #endif
     DBG1NL;
     return HardwareVer;
 }
References HARDWARE, HARDWARE, HARDWARE, HARDWARE, HARDWARE, HARDWARE.
string & MR24FDB1::getProtocolVer ()
request Protocol Version
sends a request for protocol version and stores it internally will also set a time stamp when data is received throws exeption on error
Returns
string reference to ProtocolVer
Definition at line 384 of file mr24fdb1.cpp.
 string & MR24FDB1::getProtocolVer() {
     DBG1("getProtocolVer");
     if(ProtocolVer.length()==0) {
         DBG1V_S(" No cache requesting from module ");
         sendGetAndWait(IDENT,PROTOCOL,Res_ProtocolVer_Rsp);
     }
 #if IS_1V
     dbgHexDump((const uint8_t *)ProtocolVer.c_str(),PROTOCOL_VER_LEN,false);
 #endif
     DBG1NL;
     return ProtocolVer;
 }
References IDENT, IDENT, IDENT, IDENT, IDENT, IDENT.
MR24FDB1::Presence_t MR24FDB1::getPresence (long age = 0)
get presence from module
if time since last read >age or age<0 Sends request for presence stores result in Presence will also set a time stamp when data is received else return cached value throws exeption on error
Parameters
age if stored value older than age request new
Returns
presence
Definition at line 397 of file mr24fdb1.cpp.
 MR24FDB1::Presence_t MR24FDB1::getPresence(long age) {
     DBG1("getPresence");
     if(age<=0 || millis()-Presence_ts > age) {
         DBG1V_S(" cache to old, getting new");
         sendGetAndWait(RADAR,PRESENCE,Res_Presence_Rsp);
     }
     DBG1V_S(": 0x%2.2x",Presence);
     DBG1NL;
     return Presence;
 }
References PRESENCE, PRESENCE, PRESENCE, PRESENCE, PRESENCE, PRESENCE.
Referenced by testSend(), testSend().
long MR24FDB1::getPresenceTs () inline
return last time stamp for presence
Returns
timestmap
Definition at line 835 of file mr24fdb1.h.
     long getPresenceTs() {return Presence_ts;};
float MR24FDB1::getMovement (long age = 0)
get movement
if age of cached value > age fetch new valie else return cached value
Module sends a movement report more or less every 2 sec
Parameters
age if stored value older than age request new
Returns
Movment value
Definition at line 409 of file mr24fdb1.cpp.
 float MR24FDB1::getMovement(long age) {
     DBG1("getMovement");
     if(age<=0 || millis()-Movement_ts > age) {
         DBG2V_S(" cache to old, getting new ");
         sendGetAndWait(RADAR,MOVEMENT,Res_Movement_Rsp);
     }
     DBG1V_S(": %f\n",Movement);
     DBG1NL;
     return Movement;
 }
References MOVEMENT, MOVEMENT, MOVEMENT, MOVEMENT, MOVEMENT, MOVEMENT.
Referenced by testSend(), testSend().
long MR24FDB1::getMovmentTs () inline
return last time stamp for movement
Returns
timestmap
Definition at line 853 of file mr24fdb1.h.
     long getMovmentTs() {return Movement_ts;};
Location_t MR24FDB1::getLocation () inline
get location
Definition at line 859 of file mr24fdb1.h.
     Location_t getLocation() {return Location;}
Referenced by loop().
long MR24FDB1::getLocationTs () inline
return last time stamp for location
Returns
timestmap
Definition at line 865 of file mr24fdb1.h.
     long getLocationTs(){return Location_ts;}
HeartBeat_t MR24FDB1::getHeartBeat () inline
get Heartbeat
Definition at line 870 of file mr24fdb1.h.
     HeartBeat_t getHeartBeat() {return HeartBeat;}
Referenced by loop().
long MR24FDB1::getHeartBeatTs () inline
return last time stamp for heartbeat
Returns
timestmap
Definition at line 876 of file mr24fdb1.h.
     long getHeartBeatTs(){return HeartBeat_ts;}
uint8_t MR24FDB1::getSensitivity (long age = 0)
get sensitivity parameter
if time since last read >age or age<0 Sends request for sensitivity store result in Sensitivity sets time stamp when data is received else return cached value throws exeption on error
Parameters
age if stored value older than age request new
Returns
Sensitiviy_t sensitivity
Definition at line 420 of file mr24fdb1.cpp.
 uint8_t MR24FDB1::getSensitivity(long age){
     DBG1("getSensitivity");
     if(age<=0 || millis()-Sensitivity_ts > age) {
         DBG1V_S("cache to old, getting new ");
         sendGetAndWait(SYSTEM,SENSITIVITY,Res_Sensitivity_Rsp);
     }
     DBG1V_S(": %d",Sensitivity);
     DBG1NL;
     return Sensitivity;
 }
References Res_Sensitivity_Rsp, Res_Sensitivity_Rsp, Res_Sensitivity_Rsp, Res_Sensitivity_Rsp, Res_Sensitivity_Rsp, Res_Sensitivity_Rsp.
long MR24FDB1::getSensitivity_ts () inline
return last time stamp for sensitivity
Returns
timestmap
Definition at line 898 of file mr24fdb1.h.
     long    getSensitivity_ts(){return Sensitivity_ts;};
MR24FDB1::Scene_t MR24FDB1::getScene (long age = 0)
get scene parameter
if time since last read >age or age<0 Sends request for Scene store result in Scene set a time stamp when data is received else return cached value throws exeption on error
Parameters
age if stored value older than age request new
Returns
Sensitiviy_t sensitivity
Definition at line 431 of file mr24fdb1.cpp.
 MR24FDB1::Scene_t   MR24FDB1::getScene(long age){
     DBG1("getScene");
     if(age<=0 || millis()-Scene_ts>age) {
         DBG1V_S(" cache to old, getting new");
         sendGetAndWait(SYSTEM,SCENE,Res_Scene_Rsp);
     }
     DBG1V_S(": %d",Sensitivity);
     DBG1NL;
     return Scene;
 }
long MR24FDB1::getScene_ts () inline
return last time stamp for scene
Returns
timestmap
Definition at line 919 of file mr24fdb1.h.
     long    getScene_ts() {return Scene_ts;};
UnoccupiedTime_t MR24FDB1::getUnoccupiedTime () inline
get unoccupied timeout parameter
Returns
Unccoupied_t last set time value
Definition at line 925 of file mr24fdb1.h.
     UnoccupiedTime_t getUnoccupiedTime() {return UnoccupiedTime;};
long MR24FDB1::getUnoccupiedTime_ts () inline
return last time stamp for unoccupied timer
Returns
timestmap
Definition at line 931 of file mr24fdb1.h.
     long    getUnoccupiedTime_ts() {return UnoccupiedTime_ts;};
bool MR24FDB1::getFallEnable (long age)
get status of fall enable switch
if time since last read >age or age<0 sends request for FalleEnable value store result in FeallEnable set a time stamp when data is received else return cached value throws exeption on error
Parameters
age if stored value older than age request new
Returns
true=enabled, false=disabled
Definition at line 443 of file mr24fdb1.cpp.
 bool MR24FDB1::getFallEnable(long age){
     DBG1("getFallEnable");
     if(age<=0 || millis()-FallEnable_ts > age) {
         DBG1V_S(" cache to old, getting new ");
         sendGetAndWait(OTHER,FALL_ENABLE,Res_FallEnable_Rsp);
     }
     DBG1V_S(": %s",FallEnable?"On":"Off");
     DBG1NL;
     return FallEnable;
 }
MR24FDB1::FallWarnTime_t MR24FDB1::getFallWarnTime (long age)
get status of fall warning time setting
if time since last read >age or age<0 sends request for FallWarnTime value store result in FallWarnTime set a time stamp when data is received else return cached value throws exeption on error
Parameters
age if stored value older than age request new
Returns
FallWarnTime_t FallWarnTime
Definition at line 454 of file mr24fdb1.cpp.
 MR24FDB1::FallWarnTime_t MR24FDB1::getFallWarnTime(long age){
     DBG1("getFallWarnTime");
     if(age<=0 || millis()-FallWarnTime_ts>age){
         DBG1V_S(" cache to old, getting new ");
         sendGetAndWait(OTHER,FALL_WARN_TIME,Res_FallWarnTime_Rsp);
     }
     DBG1V_S(": %s",FallWarnTime?"On":"Off");
     DBG1NL;
     return FallWarnTime;
 }
References FALL_WARN_TIME, FALL_WARN_TIME, FALL_WARN_TIME, FALL_WARN_TIME, FALL_WARN_TIME, FALL_WARN_TIME.
uint8_t MR24FDB1::getFallSensitivity (long age)
get status of fall sensitivty setting
if time since last read >age or age<0 sends request for FallSensitivity value store result in FallSensitivity set a time stamp when data is received else return cached value throws exeption on error
Parameters
age if stored value older than age request new
Returns
FallSensitivity FallWarnTime
Definition at line 465 of file mr24fdb1.cpp.
 uint8_t MR24FDB1::getFallSensitivity(long age){
     DBG1("getFallSensitivity");
     if(age<=0 || millis()-FallSensitivity_ts>age){
         DBG1V_S(" cache to old, getting new ");
         sendGetAndWait(OTHER,FALL_SENSITIVITY,Res_FallSensitivity_Rsp);
     }
     DBG1V_S(": %d",FallSensitivity);
     DBG1NL;
     return FallSensitivity;
 }
References FALL_SENSITIVITY, FALL_SENSITIVITY, FALL_SENSITIVITY, FALL_SENSITIVITY, FALL_SENSITIVITY, FALL_SENSITIVITY.
void MR24FDB1::sendSet (FuncGroups group, Functions func, uint8_t val, uint16_t len)
send a "GET" packet to the module
Sends a "set" packet Values are allways one byt with one exception: Upgrade Packet that is 4 + 1024 Bytes and is not handled here actually firemware upgrades are not implemented yet.
Parameters
group The function class to request
func The function to request
val Value to send
len length of value
Definition at line 481 of file mr24fdb1.cpp.
 void MR24FDB1::sendSet(FuncGroups fGroup, Functions func, uint8_t data, uint16_t dataLen) {
     uint8_t txPacket[]={ // construct txpacket
         MESSAGE_HEAD,   // 0 allways 55
         0x00,0x00,      // 1,2 length low high
         SET,            // 3 "Set" Function Class
         fGroup,         // 4 Function group
         func,           // 5 Function
         data,           // 6 data
         0,0             // 7-8 crc
     };
     // some commands does not have data so need to adjust length
     // shifting crc down one byte
     // TODO: this needs to be changed if/when the firmware upgrade routines are written
     uint16_t pktLen=(dataLen == 0)? sizeof(txPacket)-1:sizeof(txPacket);
     DBG2("Sending SET/%s/%s",GroupStr[fGroup],FuncStr[func]);
     DBG2V_S(" (0x%2.2x)",data);
     DBG2NL;
     // set length of packet beore crc calc...
     txPacket[1]=pktLen&0x00ff;
     txPacket[2]=pktLen&0xff00>>8;
     addCrc16(txPacket,pktLen);
 #if V3_L
     dbgHexDump(txPacket,pktLen);
 #endif
     sendPacket(txPacket,pktLen);
 }
References FuncStr, FuncStr, FuncStr, FuncStr, FuncStr, FuncStr.
Referenced by reboot(), reboot(), reboot(), reboot(), reboot(), reboot(), reboot().
void MR24FDB1::setSensitivity (uint8_t sensVal)
set sensitivity
Parameters
sensVal new sensitivity value
Definition at line 516 of file mr24fdb1.cpp.
 void MR24FDB1::setSensitivity(uint8_t sensVal){
     DBG1("Set Sensitivity");
     DBG1V_S(":  %d\n",sensVal);
     DBG1NL;
     sendSet(SYSTEM,SENSITIVITY,sensVal,1);
 }
References SENSITIVITY, SENSITIVITY, SENSITIVITY.
Referenced by setup().
void MR24FDB1::setScene (Scene_t newScene)
set scene
Parameters
newScene scene to set
Definition at line 523 of file mr24fdb1.cpp.
 void MR24FDB1::setScene(Scene_t newScene) { // gives incoorrect responce: system/sensitvity
     DBG1("Set Scene");
     if(newScene>HOTEL_SC) {
         DBG1NL;
         ERROR("Invalid scene 0x%02.2x\n",newScene);
         throw MR24FDB1_Exception( Res_InvScene, SET,OTHER,SCENE);
     }
     DBG1V_S(": 0x%02.2x => %s",newScene,SceneStr[newScene]);
     DBG1NL;
     sendSet(SYSTEM,SCENE,newScene,1);
 }
References HOTEL_SC, HOTEL_SC, HOTEL_SC, HOTEL_SC, HOTEL_SC, HOTEL_SC, HOTEL_SC, HOTEL_SC.
Referenced by setup().
void MR24FDB1::setUnoccupiedTime (UnoccupiedTime_t time)
set unoccupied timeut
Parameters
time value to set
Definition at line 535 of file mr24fdb1.cpp.
 void MR24FDB1::setUnoccupiedTime(UnoccupiedTime_t time) { // gives incoorrect responce: system/sensitvity
     DBG1("Set Unoccupied Timeout");
     if(time>UT_60M) {
         DBG1NL;
         ERROR("Invalid time 0x%02.2x\n",time);
         throw MR24FDB1_Exception( Res_InvScene, SET,OTHER,SCENE);
     }
     DBG1V_S(": 0x%02.2x",time);
     DBG1NL;
     sendSet(SYSTEM,UNOCCUPIED_TIME,time,1);
 }
References OTHER, OTHER, OTHER, OTHER, OTHER, OTHER, OTHER, OTHER.
Referenced by setup().
MR24FDB1::Result_t MR24FDB1::reboot ()
reboot
sends a reboot command
Definition at line 550 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::reboot() {
     MR24FDB1::Result_t result;
     DBG1("Rebooting Module ... \n");
     Status=Res_Undefined;
     sendSet(OTHER,REBOOT,0,0);
     result=waitFor( Res_InitSuccess);
     DBG1V("reboot: got 0%02.2x =>%s\n",result,MR24FDB1_Exception::ResStr[result]);
     if(result != Res_InitSuccess) {
         WARN("No init succes after reboot!\n");
     }
     return result;
 // should probably wait around here for a bit and clear out garbage comming from module during reboot
 }
References OTHER, OTHER, OTHER, OTHER, OTHER, OTHER, OTHER, OTHER.
Referenced by loop().
void MR24FDB1::startUpgrade (uint32_t size, uint8_t * versionP, uint16_t verLen)
send an upgrade packet
NOT IMPLEMENTED
Parameters
size firmware size
versionP pointer to version info
verLen length of version info
Definition at line 567 of file mr24fdb1.cpp.
 void MR24FDB1::startUpgrade(uint32_t offset, uint8_t * versionP,uint16_t verLen){
     ERROR("startUpgrade not implented\n");
     throw MR24FDB1_Exception( Res_Unimplmented, SET,OTHER,UPGRADE);
 }
References OTHER, OTHER, OTHER, OTHER.
void MR24FDB1::sendUpgradePacket (uint32_t offset, uint8_t * packetP)
send an upgrade packet
NOT IMPLEMENTED also, question are packets allways 1024 bytes and is offset in bytes or packets
Parameters
offset offset of packet
packetP pointer to packet of 1024 bytes
Definition at line 572 of file mr24fdb1.cpp.
 void MR24FDB1::sendUpgradePacket(uint32_t offset, uint8_t * buffP){
     ERROR("sendUpgradePacket not implented\n");
     throw MR24FDB1_Exception( Res_Unimplmented, SET,OTHER,UPGRADE_PKT);
 }
References OTHER, OTHER, OTHER, OTHER.
void MR24FDB1::endOfUpgrade ()
Send end of upgrade packet.
Signals end of upgrade process to the module module should respond with a Report/Identification/Software Version ie 0x04 0x01 0x02
Definition at line 577 of file mr24fdb1.cpp.
 void MR24FDB1::endOfUpgrade(){
     ERROR("endOfUpgrade not implented\n");
     throw MR24FDB1_Exception( Res_Unimplmented, SET,OTHER,END_OF_UPGRADE);
 };
References END_OF_UPGRADE, END_OF_UPGRADE, END_OF_UPGRADE, END_OF_UPGRADE.
void MR24FDB1::setFallDetect (bool onOff)
enable / disable fall detection
Parameters
onOff true=enabled , false=disabled
Definition at line 582 of file mr24fdb1.cpp.
 void MR24FDB1::setFallDetect(bool onOff) {
     DBG1("SetFallDetect");
     DBG1V_S(": %s\n",onOff?"Enable":"Disable");
     DBG1NL;
     sendSet(OTHER,FALL_ENABLE,onOff?1:0,1);
 }
References FALL_ENABLE, FALL_ENABLE, FALL_ENABLE.
Referenced by setup().
void MR24FDB1::setFallWarnTime (FallWarnTime_t fallTime)
set fall warn time parameter
Parameters
fallTime
Definition at line 589 of file mr24fdb1.cpp.
 void MR24FDB1::setFallWarnTime(FallWarnTime_t fallTime){
     DBG1("setFallWarnTime");
     DBG1V_S(": %d\n",fallTime);
     DBG1NL;
     sendSet(OTHER,FALL_WARN_TIME,fallTime,1);
 }
References FALL_WARN_TIME, FALL_WARN_TIME, FALL_WARN_TIME.
void MR24FDB1::setFallSensitivity (uint8_t sensVal)
set fall detection sensitivity
Parameters
sensVal value from 1 - 10
Definition at line 596 of file mr24fdb1.cpp.
 void MR24FDB1::setFallSensitivity(uint8_t fallSensVal){
     DBG1("setFallSensistivity");
     DBG1V_S(": %d\n",fallSensVal);
     DBG1NL;
     sendSet(OTHER,FALL_SENSITIVITY,fallSensVal,1);
 }
References FALL_SENSITIVITY, FALL_SENSITIVITY, FALL_SENSITIVITY.
void MR24FDB1::dumpPacket (int length = 0)
dumpt packet in hex/asci format
Dumps content of packet in hexformat and ascii if length param=0 then use packets own length field
Parameters
length length of packet to dump
Definition at line 1136 of file mr24fdb1.cpp.
 void MR24FDB1::dumpPacket(int length) {
     dbgHexDump((uint8_t *) &Packet,(length==0)?Packet.length:length+1);
 }
MR24FDB1::Result_t MR24FDB1::testSend ()
send test
Continously request presence and movement System will hang in endless loop if invoked
Definition at line 1139 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::testSend() {
 #define GREEN_LED 25
 #define YELLOW_LED 26
 #define RED_LED 27
     Result_t result;
     int count=0;
     int count2=0;
     /*
     pinMode(GREEN_LED,OUTPUT);
     pinMode(YELLOW_LED,OUTPUT);
     pinMode(RED_LED,OUTPUT);
     */
     INFO("testSend\n");
     while(true) {
         printf("[%d] getting Presence:\n",count++);
         getPresence(1);
         readPacket();
         parsePacket();
         getMovement(1);
         readPacket();
         parsePacket();
     }
 }
References getMovement(), getMovement(), getMovement(), getMovement().
MR24FDB1::Result_t MR24FDB1::decodeRadar (MR24FDB1::FuncClasses fClass) private
parse Radar group responces and reports
decode RADAR type resports and responces set class variable and timestampps and return corresponding Res_..._Rsp on successfull decode
Parameters
fClass the class handler that called (responce or report)
Returns
Res_..._Rsp on successful decode;
Definition at line 965 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::decodeRadar(MR24FDB1::FuncClasses fClass){
     MR24FDB1::Result_t retVal;
     uint32_t longVal;
     DBG2_S("Radar/");
     switch(Packet.func) { // --- Presence
         case PRESENCE:
             DBG2_S("Presence");
             switch(Packet.lval & 0x00FFFFFF) {
                 case P_NOBODY_BP:
                     DBG2V_S(": Nobody detected");
                     Presence=P_NOBODY;
                     break;
                 case P_PRESENT_BP:
                     DBG2V_S(": Presence detected");
                     Presence=P_PRESENT;
                     break;
                 case P_MOVING_BP:
                     DBG2V_S(": Movement detected");
                     Presence=P_MOVING;
                     break;
                 default:
                     DBG2NL;
                     ERROR("Inv presence type received : 0x%02.2x 0x%02.2x 0x%02.2x \n",Packet.presence[0] , Packet.presence[1], Packet.presence[2]);
                     throw MR24FDB1_Exception( Res_InvPresence,fClass,Packet.funcGroup,Packet.func,longVal);
                     break;
             }
             Presence_ts=millis();
             retVal=(fClass==REPORT)?Res_Presence:Res_Presence_Rsp;
             break;
         // --- Movement
         case MOVEMENT:
             DBG2_S("Movement");
             Movement=Packet.movement;
             Movement_ts=millis();
             retVal=fClass==REPORT?Res_Movement:Res_Movement_Rsp;
             DBG2V_S(": %4.1f",Movement);
             break;
         // --- Location
         // Only happens in responces
         case LOCATION:
             DBG2_S("Location");
             longVal = Packet.location[0] | Packet.location[1]<<8 | Packet.location[2]<<16;
             switch(longVal) {
                 case L_STATIONARY_BP:
                     DBG2V_S(": Stationary no one detected");
                     Location = L_STATIONARY;
                     break;
                 case L_CLOSE_BP:
                     DBG2V_S(": Someone is Close");
                     Location = L_CLOSE;
                     break;
                 case L_AWAY_BP:
                     DBG2V_S(": Someone Far");
                     Location = L_AWAY;
                     break;
                 case L_APROACHING_BP:
                     DBG2V_S(": Somenone is Aproaching");
                     Location = L_APROACHING;
                     break;
                 case L_LEAVING_BP:
                     DBG2V_S(": Someone is leaving");
                     Location = L_LEAVING;
                     break;
                 default:
                     DBG2NL;
                     ERROR("Inv location indicator: 0x%02.2x 0x%02.2x 0x%02.2x 0x%02.2x\n",Packet.location[0],Packet.location[1],Packet.location[2]);
                     throw MR24FDB1_Exception(Res_InvLocation,fClass,RADAR,LOCATION, longVal);
                     break;
             }
             Location_ts=millis();
             retVal=Res_Location;
             break;
         default:
             DBG2NL;
             ERROR("Inv Radar function: 0%02.2x\n",Packet.func);
             throw MR24FDB1_Exception(Res_InvRadarFunc,fClass,RADAR,Packet.func);
             break;
     }
     return retVal;
 }
References LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION, LOCATION.
Referenced by parseReport(), parseReport().
void MR24FDB1::sendPacket (uint8_t * txPacket, int len) private
send a packet to the module
Module will respond with a responce packet
Parameters
txPacket Packet to transmit
len length of packet to send
Returns
Res_ok if transmission successfull
Definition at line 266 of file mr24fdb1.cpp.
 void MR24FDB1::sendPacket(uint8_t *txPacket,int len) {
     int count=0;
 #if IS_VERB_L
     if(DbgLevel&DBG_VERB_L) {
         printf("SendPacket:");
         dbgHexDump(txPacket,len);
         putchar('\n');
     }
 #endif
     while(Serial2.availableForWrite()<len) {
         delay(1);
         count++;
         if(count>1000) {
             FAIL("Transmit buffer never empties\n");
             throw MR24FDB1_Exception( Res_Timeout,0,0,0);
         }
     }
     Serial2.write(txPacket,len);
 }
References Res_Timeout.
Referenced by sendGet(), sendGet().
MR24FDB1::Result_t MR24FDB1::parseResponce () private
parse reponce type packet
parse an responce packet
Returns
Result_t Res_..._Rsp if valid responce decoded
Exceptions
exception on fail
Definition at line 635 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::parseResponce() {
     uint32_t longVal;
     Result_t retVal=Res_InvRep;
     DBG2("Got: RESPONCE/");
     switch(Packet.funcGroup) {
         case IDENT:
             DBG2_S("Ident/");
             switch(Packet.func) {
                 case DEVICE:
                     DBG2_S("Device ID");
                     Packet.deviceID[DEVICE_ID_LEN]='\0';
                     DeviceId= string((char *) Packet.deviceID);
                     retVal=Res_DeviceId_Rsp;
                     DBG2V_S(": %s",DeviceId.c_str());
                     break;
                 case SOFTWARE:
                     DBG2_S("Software Ver");
                     Packet.softwareVer[SOFTWARE_VER_LEN]='\0';
                     SoftwareVer=string((char *) Packet.softwareVer);
                     retVal=Res_SoftwareVer_Rsp;
                     DBG2V_S(": %s",SoftwareVer.c_str());
                     break;
                 case HARDWARE:
                     DBG2_S("Hardware Version");
                     Packet.hardwareVer[HARDWARE_VER_LEN]='\0';
                     HardwareVer=string((char *) Packet.hardwareVer);
                     retVal=Res_HardwareVer_Rsp;
                     DBG2V_S(": %s",HardwareVer.c_str());
                     break;
                 case PROTOCOL:
                     DBG2_S("Protocol Version");
                     Packet.protocolVer[PROTOCOL_VER_LEN]='\0';
                     ProtocolVer=string((char *) Packet.protocolVer);
                     DBG2V_S(": %s",ProtocolVer.c_str());
                     retVal=Res_ProtocolVer_Rsp;
                     break;
                 default:
                     DBG2NL;
                     WARN("Uknown Identification function: 0%02.2x\n");
                     throw MR24FDB1_Exception( Res_InvIdentFunc,RESPONCE,IDENT,Packet.func);
             }
             break;
         case  RADAR:
             retVal=decodeRadar(RESPONCE);
             break;
         case SYSTEM:
             DBG2_S("System/");
             switch(Packet.func) {
                 case SENSITIVITY:
                     DBG2_S("Sensitivity");
                     retVal=Res_Sensitivity_Rsp;
                     Sensitivity=Packet.sensitivity;
                     Sensitivity_ts=millis();
                     DBG2V_S(": %d (0x%02.2x)",Sensitivity,Sensitivity);
                     break;
                 case SCENE:
                     DBG2_S("Scene");
                     retVal=Res_Scene_Rsp;
                     Scene=static_cast<Scene_t>(Packet.scene);
                     Scene_ts=millis();
                     DBG2V_S(": %s", SceneStr[Scene]);
                     break;
                 case UNOCCUPIED_TIME:
                     DBG2_S("Unoccupied:");
                     retVal=Res_UnoccupiedTime_Rsp;
                     UnoccupiedTime=static_cast<UnoccupiedTime_t>(Packet.unoccupiedTime);
                     UnoccupiedTime_ts=millis();
                     DBG2V_S(": 0%02.2x", UnoccupiedTime);
                     break;
                 default:
                     DBG2NL;
                     ERROR("Uknown system function: 0x%02.2x\n",Packet.func);
                     throw(Res_InvRspFunc,RESPONCE,SYSTEM,Packet.func);
                     break;
             }
             break;
         case OTHER:
             DBG2_S("Other/");
             switch(Packet.func) {
                 case UPGRADE:   // ota upgrade start ACK
                     DBG2_S("Upgrade Start ACK");
                     UpgradeStartAck=Packet.upgradeStartAck;
                     UpgradeStartAck_ts=millis();
                     retVal=(UpgradeStartAck  == 0)? Res_UpgradeStartFail_Rsp:Res_UpgradeStartOk_Rsp;
                     DBG2V_S(": %s",UpgradeStartAck == 0? "Failed":"Ok");
                     break;
                 case FALL_ENABLE:
                     DBG2_S("Fall switch Enable");
                     FallEnable=Packet.fallEnable;
                     FallEnable_ts=millis();
                     retVal=Res_FallEnable_Rsp;
                     DBG2V_S(": %s",FallEnable==0?"Off":"On");
                     break;
                 case FALL_WARN_TIME:        //
                     DBG2_S("Fall warning time");
                     if (Packet.fallWarningTime>MIN_30) {
                         throw(Res_InvFallWarnTime,RESPONCE,OTHER,Packet.func,Packet.fallWarning);
                     }
                     FallWarnTime=static_cast<FallWarnTime_t>(Packet.fallWarningTime);
                     FallWarnTime_ts=millis();
                     retVal=Res_FallWarnTime_Rsp;
                     DBG2V_S(": %d",FallWarnTime);
                     break;
                 case FALL_SENSITIVITY:      // Responce to Set sensitivity
                     DBG2_S("Fall sensitivity");
                     FallSensitivity=Packet.fallSensitivity;
                     FallSensitivity_ts=millis();
                     retVal=Res_FallSensitivity_Rsp;
                     DBG2V_S(": %d",FallSensitivity);
                     break;
                 default:
                     DBG2NL;
                     ERROR("Inv function 0x%02.2x\n",Packet.func);
                     throw(Res_InvRspFunc,RESPONCE,OTHER,Packet.func);
                     break;
             }
             break;
         default:
             DBG2NL;
             ERROR("Inv group 0x%02.2x\n",Packet.funcClass);
             throw(Res_InvRspFunc,RESPONCE,Packet.funcClass,Packet.func);
             break;
     }
     DBG2NL;
     return retVal;
 }
References DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE, DEVICE.
Referenced by parsePacket().
MR24FDB1::Result_t MR24FDB1::parseReport () private
parse report type packet
parse an active report packet
Returns
Result_t Res_..._Rsp if valid responce decoded
Exceptions
exception on fail
— Heart beat
— Software -> reset
Definition at line 783 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::parseReport() {
     DBG2("REPORT/");
     uint32_t longVal;
     Result_t retVal=Res_InvRep;
     switch(Packet.funcGroup) {
         // -- Identitiy --
         case IDENT:                 // Sent afte successfull upgrade
             DBG2_S("Ident/");
             if(Packet.func != SOFTWARE) {  // only 1 func in this group
                 DBG1NL;
                 ERROR("Inv function in IDENT group received : 0x%02.2x\n",Packet.func);
                 throw MR24FDB1_Exception( Res_InvIdentFunc,REPORT,IDENT,Packet.func);
             }
             DBG2_S("Software");
             DBG2V_S(": Upgrade success");
             UpgradeStatus = Res_UpgradeSuccess;
             retVal= Res_UpgradeSuccess;
             break;
         // -- Radar group --
         case RADAR:                 // Radar reports
             retVal=decodeRadar(REPORT);
             break;
         // --- Other
         case OTHER:
             DBG2_S("Other/");
             switch(Packet.func) {
                 case HEARTBEAT:
                     DBG2_S("Heart Beat");
                     longVal = Packet.heartBeat[0] | Packet.heartBeat[1]<<8 | Packet.heartBeat[2]<<16;
                     switch(longVal) {
                         case HB_NONE_BP:
                             DBG2V_S(": No one present ");
                             HeartBeat = HB_NONE;
                             break;
                         case HB_STATIONARY_BP:
                             DBG2V_S(": Stationary");
                             HeartBeat = HB_STATIONARY;
                             break;
                         case HB_MOVEMENT_BP:
                             DBG2V_S(": Movment detected");
                             HeartBeat = HB_MOVEMENT;
                             break;
                         default:
                             DBG2NL;
                             ERROR("Inv heart beat : 0x%02.2x 0x%02.2x 0x%02.2x\n",Packet.heartBeat[0] , Packet.heartBeat[1] , Packet.heartBeat[2]);
                             throw MR24FDB1_Exception(Res_InvHeartBeat,REPORT,OTHER,HEARTBEAT, longVal);
                             break;
                     }
                     HeartBeat_ts=millis();
                     retVal=Res_HeartBeat;
                     break;
                 case SOFTWARE:  // Abnormal reset
                     DBG2NL;
                     if(Packet.abnReset == 0x0F ) {
                         WARN("Abnormal Reset\n");
                         retVal = Res_Reset;
                     } else {
                         ERROR("Inv Reset Class : 0x%02.2x\n",Packet.abnReset);
                         throw MR24FDB1_Exception(Res_InvReset,REPORT,OTHER,SOFTWARE,Packet.abnReset);
                     }
                     break;
                 case INIT_SUCCESS:
                     DBG2_S("Init Success");
                     Status=retVal=Res_InitSuccess;
                     break;
                 default: // Inv Other group
                     DBG2NL;
                     ERROR("Inv Other Function : 0x%02.2x\n",Packet.func);
                     throw MR24FDB1_Exception(Res_InvOtherFunc,REPORT,OTHER,Packet.func);
             }
             break;
         default: // Inv Rerport group
             DBG2NL;
             ERROR("Inv Report group: 0x%02.2x\n",Packet.funcGroup);
             throw MR24FDB1_Exception(Res_InvRepGroup,REPORT,Packet.funcGroup,Packet.func);
     }
     DBG2NL;
     return retVal;
 };
References HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT, HB_MOVEMENT.
Referenced by parsePacket().
MR24FDB1::Result_t MR24FDB1::parseFallReport () private
parse fall type packet
Returns
Result_t Res_..._Rsp if valid responce decoded
Exceptions
exception on fail
Definition at line 882 of file mr24fdb1.cpp.
 MR24FDB1::Result_t MR24FDB1::parseFallReport() {
     FallAlarm=NO_FALL_DATA;
     DBG2("FALL/");
     switch(Packet.funcGroup) {
         case F_ALARM_CL:
             DBG2_S("ALARM: ");
             switch(Packet.func) {
                 case F_ALARM:
                     switch (Packet.fallAlarm) {
                         case F_SUSPECTED:
                             DBG2V_S(": Suspected fall detected.");
                             FallAlarm=F_SUSPECTED;
                             break;
                         case F_REAL:
                             DBG2V_S(": Real fall detected.");
                             FallAlarm=F_REAL;
                             break;
                         case F_NO_FALL:
                             DBG2V_S(": No fall detected.n");
                             FallAlarm=F_NO_FALL;
                             break;
                         default:
                             DBG2NL;
                             FallAlarm=NO_FALL_DATA;
                             ERROR("An invalid fall alarm type (%2.2x) was received\n",Packet.fallAlarm);
                             throw MR24FDB1_Exception(Res_InvFallAlarm,F_ALARM_CL,FALL,Packet.fallAlarm);
                             break;
                     } // fallAlarm func
                     break;
                 case F_WARNING:
                     DBG2_S("WARNING");
                     switch (Packet.fallWarning){
                         case NO_FALL_WARNING:
                             DBG2V_S(": No warning message at this time.");
                             FallWarning=NO_FALL_WARNING;
                         break;
                         case FALL_WARNING_1:
                             DBG2V_S(": First fall Warning\n");
                             FallWarning=FALL_WARNING_1;
                         break;
                         case FALL_WARNING_2:
                             DBG2V_S(": Second fall warning\n");
                             FallWarning=FALL_WARNING_2;
                             break;
                         case FALL_WARNING_3:
                             DBG2V_S(": Third fall warning\n");
                             FallWarning=FALL_WARNING_3;
                             break;
                         case FALL_WARNING_4:
                             DBG2V_S(": Fourth fall warning\n");
                             FallWarning=FALL_WARNING_4;
                             break;
                         default:
                             DBG2NL;
                             ERROR("An invalid fall Warning type (%2.2x) was received\n",Packet.fallWarning);
                             throw MR24FDB1_Exception(Res_InvFallWarnCount,FALL,F_ALARM_CL,F_WARNING,Packet.fallWarning);
                             break;
                     } // Warning func
                     break;
                 default:
                     DBG2NL;
                     ERROR("An invalid Fall Radar Alarm Type was received (%d)\n",Packet.func);
                     throw MR24FDB1_Exception(Rea_InvFallAlarmFunc,FALL,F_ALARM_CL,Packet.func);
                     break;
             } // Alarm group
             break;
         default:
             DBG2NL;
             ERROR("Invalid Fall group (%2.2x)\n", Packet.funcGroup);
             throw MR24FDB1_Exception(Res_InvFallGroup,FALL,Packet.funcGroup,0);
             break;
     }
     DBG2NL;
     return MR24FDB1::Res_Fall;
 }
Referenced by parsePacket().
uint16_t MR24FDB1::calculateCrc16 (uint8_t * frameP, uint16_t len) private
calculate crc16 of current packet
Parameters
frameP pointer to buffer
len to calculcate over
Returns
calculated crc
Definition at line 1124 of file mr24fdb1.cpp.
 uint16_t MR24FDB1::calculateCrc16(uint8_t *frameP, uint16_t len){
     uint8_t crcHi = 0xFF;
     uint8_t crcLo = 0xFF;
     int index=0;
     while(len--){
         index = crcLo ^ *frameP++;
         crcLo = ( crcHi ^ crcHiTab[index]);
         crcHi = crcLoTab[index];
     }
     return (uint16_t)(crcLo << 8 | crcHi);
 }
uint16_t MR24FDB1::calculateCrc16 () private
calculate crc16 of current packet
Returns
uint16_t crc calculated crc
Definition at line 1119 of file mr24fdb1.cpp.
 uint16_t MR24FDB1::calculateCrc16(){
     return calculateCrc16((uint8_t *)&Packet, Packet.length-1);
 }
Referenced by addCrc16(), addCrc16().
uint16_t MR24FDB1::addCrc16 (uint8_t * frameP, uint16_t len) private
calculate and add crc16 at end of buffer
buffer must be large enough crc low and high byte is added to frameP[len-2] and frameP[len-1] respectively
Parameters
frameP pointer to buffer
len to calculcate over
Returns
crc calculated crc
Definition at line 1101 of file mr24fdb1.cpp.
 uint16_t MR24FDB1::addCrc16(uint8_t *frameP,uint16_t len) {
     DBG3(" Adding crc");
     #pragma pack(1)
     union {
         uint16_t w;
         uint8_t b[2];
     } crc;
     #pragma pack()
     crc.w=calculateCrc16(frameP,len-2);
     frameP[len-1]=crc.b[0];
     frameP[len-2]=crc.b[1];
     DBG3V_S(": %d - 0x%2.2x 0x%2.2x", crc.w, crc.b[0],crc.b[1]);
     DBG3NL;
     return(crc.w);
 }
References calculateCrc16(), calculateCrc16().
Referenced by sendGet(), sendGet().
Friends And Related Function Documentation
friend class MR24FDB_Exception friend
Definition at line 268 of file mr24fdb1.h.
Member Data Documentation
const int MR24FDB1::DEVICE_ID_LEN =12 static
Length of device id data.
Definition at line 270 of file mr24fdb1.h.
Referenced by getDeviceId(), getDeviceId().
const int MR24FDB1::HARDWARE_VER_LEN =8 static
Length of hardware version data.
Definition at line 271 of file mr24fdb1.h.
Referenced by getHardwareVer(), getHardwareVer().
const int MR24FDB1::SOFTWARE_VER_LEN =8 static
Lenght of software version data.
Definition at line 272 of file mr24fdb1.h.
Referenced by getSoftwareVer(), getSoftwareVer().
const int MR24FDB1::PROTOCOL_VER_LEN =8 static
Length of protocol version data.
Definition at line 273 of file mr24fdb1.h.
Referenced by getProtocolVer(), getProtocolVer().
const int MR24FDB1::MAXPACKET_DATA_LENGTH = 50 static
max data length
Definition at line 274 of file mr24fdb1.h.
const uint8_t MR24FDB1::MESSAGE_HEAD = 0x55
Data frame header.
Definition at line 321 of file mr24fdb1.h.
Referenced by readPacket(), readPacket(), readPacket().
const unsigned long MR24FDB1::MAX_SERIAL_WAIT_TIME = 2000 static
max time in ms to wait for serial char to arrive
Definition at line 322 of file mr24fdb1.h.
Referenced by readByte().
const int MR24FDB1::MAXPACKET_LENGTH = sizeof(Packet_t) static
max length of a packet from the chip
Definition at line 323 of file mr24fdb1.h.
Referenced by readPacket().
const char * MR24FDB1::ClassStr static
Initial value:
{
     "NoClass",
     "GET",
     "SET",
     "RESPONCE",
     "REPORT",
     "FALL"
}
string representations of code/class/func/Scene etc
Text representation of function classes
Definition at line 328 of file mr24fdb1.h.
Referenced by MR24FDB1_Exception::decodeError().
const int MR24FDB1::ClassStrCount =COUNT(ClassStr) static
Number of function class strings.
Definition at line 329 of file mr24fdb1.h.
Referenced by MR24FDB1_Exception::decodeError().
const char * MR24FDB1::GroupStr static
Initial value:
{
     "NoGroup",
     "IDENT",
     "Uknown 2",
     "RADAR",
     "SYSTEM",
     "OTHER"
}
Text representation of function groups.
Definition at line 331 of file mr24fdb1.h.
Referenced by sendGet(), sendGet(), sendGet().
const int MR24FDB1::GroupStrCount = COUNT(GroupStr) static
Number of function group strings.
Definition at line 332 of file mr24fdb1.h.
Referenced by MR24FDB1_Exception::decodeError().
const char * MR24FDB1::FuncStr static
Initial value:
{
        "NoFunc",
        "Device - Heartbeat",
        "Software",
        "Hardware",
        "Protocol",
        "Presence",
        "Movement",
        "Location",
        "Upgrade",
        "Upgrade pkt - ACK",
        "Init Success",
        "Fall enable",
        "Sensitivity",
        "Unkown Func 0x0D",
        "Fall Sensitivity",
        "Uknown Func 0x0F",
        "Scene",
        "Uknown Func 0x11",
        "UnOccupied Time",
}
Text representation of functions.
Definition at line 334 of file mr24fdb1.h.
const int MR24FDB1::FuncStrCount = COUNT(FuncStr) static
Number of function strings.
Definition at line 335 of file mr24fdb1.h.
const char * MR24FDB1::SceneStr static
Initial value:
{
    "Default",
    "Area detection",
    "Bathroom",
    "Bedroom",
    "Living Room",
    "Office",
    "Hotell"
}
Text representation of scenes.
Definition at line 337 of file mr24fdb1.h.
Referenced by parseResponce(), parseResponce().
const int MR24FDB1::SceneStrCount = COUNT(SceneStr) static
Number of function strings.
Definition at line 338 of file mr24fdb1.h.
const char * MR24FDB1::UnoccupiedTimeStr static
Initial value:
{
    "no Timeout",
    "10 Sec",
    "30 Sec",
    "1 Min",
    "2 Min",
    "5 Min",
    "10 Min",
    "30 Min",
    "60 Min",
}
Text represntations of Unoccupied settings.
Definition at line 340 of file mr24fdb1.h.
const int MR24FDB1::UnoccupiedTimeStrCount = COUNT(SceneStr) static
Number of Unoccupied settings strings.
Definition at line 341 of file mr24fdb1.h.
uint8_t MR24FDB1::RXBit
Definition at line 629 of file mr24fdb1.h.
Referenced by MR24FDB1().
uint8_t MR24FDB1::TXBit
Definition at line 630 of file mr24fdb1.h.
Referenced by MR24FDB1().
Packet_t MR24FDB1::Packet
incoming packet from radar module
Definition at line 633 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1().
bool MR24FDB1::PacketReceived = false
a valid packet has been received
Definition at line 634 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
Result_t MR24FDB1::Status
Current status running fault, reset....
Definition at line 636 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::Status_ts
Last time changed.
Definition at line 637 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
Result_t MR24FDB1::UpgradeStatus
Definition at line 639 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::UpgradeStatus_ts
Definition at line 640 of file mr24fdb1.h.
Referenced by MR24FDB1().
Presence_t MR24FDB1::Presence
last active report Envrioment Status
Definition at line 642 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::Presence_ts
Presence time stamp.
Definition at line 643 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
float MR24FDB1::Movement
movment strengtht
Definition at line 645 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::Movement_ts
time stamp;
Definition at line 646 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
Location_t MR24FDB1::Location
location far, close none
Definition at line 648 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::Location_ts
time stamp;
Definition at line 649 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
HeartBeat_t MR24FDB1::HeartBeat
Heartbeat detection.
Definition at line 651 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::HeartBeat_ts
time stamp;
Definition at line 652 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
uint8_t MR24FDB1::Sensitivity
senstitivity setting 0-0x0A
Definition at line 654 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::Sensitivity_ts
time stamp;
Definition at line 655 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
Scene_t MR24FDB1::Scene
Scene setting.
Definition at line 657 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::Scene_ts
Time stamp.
Definition at line 658 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
UnoccupiedTime_t MR24FDB1::UnoccupiedTime
Unoccupied time.
Definition at line 660 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::UnoccupiedTime_ts
Time stamp.
Definition at line 661 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
bool MR24FDB1::FallEnable
Definition at line 663 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::FallEnable_ts
Definition at line 664 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
FallAlarm_t MR24FDB1::FallAlarm
latest fall status
Definition at line 666 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::FallAlarm_ts
time stamp;
Definition at line 667 of file mr24fdb1.h.
Referenced by MR24FDB1().
FallWarnCount_t MR24FDB1::FallWarning
last fallwarning received
Definition at line 669 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::FallWarning_ts
time stamp;
Definition at line 670 of file mr24fdb1.h.
Referenced by MR24FDB1().
FallWarnTime_t MR24FDB1::FallWarnTime
last fallwarning time received
Definition at line 672 of file mr24fdb1.h.
Referenced by getFallWarnTime(), getFallWarnTime().
long MR24FDB1::FallWarnTime_ts
time stamp;
Definition at line 673 of file mr24fdb1.h.
Referenced by getFallWarnTime(), getFallWarnTime().
uint8_t MR24FDB1::FallSensitivity
last fallwarning received
Definition at line 675 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
long MR24FDB1::FallSensitivity_ts
time stamp;
Definition at line 676 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
bool MR24FDB1::UpgradeStartAck
Definition at line 678 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1().
long MR24FDB1::UpgradeStartAck_ts
Definition at line 679 of file mr24fdb1.h.
string MR24FDB1::DeviceId
device id
Definition at line 682 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
string MR24FDB1::SoftwareVer
Software Version.
Definition at line 683 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
string MR24FDB1::HardwareVer
Software Version.
Definition at line 684 of file mr24fdb1.h.
Referenced by getHardwareVer(), getHardwareVer().
string MR24FDB1::ProtocolVer
Protocl Version.
Definition at line 685 of file mr24fdb1.h.
Referenced by MR24FDB1(), MR24FDB1(), MR24FDB1().
bool MR24FDB1::GotResponce
Definition at line 688 of file mr24fdb1.h.
Referenced by MR24FDB1().
The documentation for this class was generated from the following files:
mr24fdb1.h
mr24fdb1.cpp